### ISSUE TITLE
Made EA Installer for fonts

### ISSUE THREAD

**Issue by MokhaLeee** [mitltl/FE_Font_tiles_generator#1]
感谢你的分享！
进一步地，基于生成的字库图片，我制作了EA Installer，以实现更好的内存控制与文本化输入。可以直接用本仓库生成的字模直接生成EA文本。
https://github.com/MokhaLeee/PyGenerator-FE-UTF8Font-Installer.git
https://github.com/MokhaLeee/FE8U-cnFont-EAInstaller.git

**Comment by mitltl** [comment]
有一种被鞭尸的感觉。😂 让我想起了不成熟时期瞎搞的东西。现在想想自己当年的规范都觉得羞耻。

Anywanys, have fun. feel free to do anything about gba fe modding.
